from django.urls import path

from adminapp import views

urlpatterns = [
    path('',views.adminhome,name='home'),
    path('catall',views.categoryall,name='catall'),
    path('catadd',views.categoryadd,name='catadd'),
    path('catedit/<int:cid>/',views.catedit,name='catedit'),
    path('custall',views.customerall,name='custall'),
    path('custedit/<int:cid>/',views.customeredit,name='custedit'),
    path('custdeactive/<int:did>/',views.CustDeactive,name='deact'),
    path('custactive/<int:did>/',views.CustActivate,name='act'),
    path('trainerlist',views.Trainer_Approved_List,name='tal'),
    path('trainerapproval',views.Trainer_Approvals,name='ta'),
    path('trainerapproved/<int:aid>/',views.Trainer_Approving_function,name='tad'),
    path('staff_registration',views.staff_registration,name='staff_reg'),
    path('staffall',views.staffall,name='staffall'),
    path('staffedit/<int:cid>/', views.staffedit, name='staffedit'),
    path('staffdeactive/<int:did>/',views.staffDeactive,name='staffdeact'),
    path('staffactive/<int:did>/',views.staffActivate,name='staffact'),
    path('subcatadd',views.subcategoryadd,name='subcatadd'),
    path('subcatedit/<int:cid>/',views.subcatedit,name='subcatedit'),
    path('subcatall',views.subcategoryall,name='subcatall'),
    path('tutorialadd',views.tutorialadd,name='tadd'),
    path('tutorialall',views.tutorialall,name='tall'),
    path('tutorialedit/<int:id>/',views.tutorialedit,name='tutoedit'),
    path('database-to-excelcust/', views.database_to_excelcust, name='database_to_excelcust'),
    path('database-to-excelstaff/', views.database_to_excelstaff, name='database_to_excelstaff'),
    path('database-to-exceltrainer/', views.database_to_exceltrainer, name='database_to_exceltrainer'),
    path('database-to-excelsales/', views.database_to_excelsales, name='database_to_excelsales'),
    path('database-to-excelcat/', views.database_to_excelcat, name='database_to_excelcat'),
    path('database-to-excelsubcat/', views.database_to_excelsubcat, name='database_to_excelsubcat'),
    path('database-to-exceltutorial/', views.database_to_exceltutorial, name='database_to_exceltutorial'),

    path('staffDiet', views.StaffDietRequest, name='streq'),
    path('stafconfirmationdiet/<int:id>/',views.StaffRequestConfirmation,name='stdc'),
    path('generate_pdf',views.generate_pdf,name='generate_pdf'),
    path('generate_pdfstaff',views.generate_pdfstaff,name='generate_pdfstaff'),
    path('generate_pdftrainer',views.generate_pdftrainer,name='generate_pdftrainer'),
    path('generate_pdfcategory',views.generate_pdfcategory,name='generate_pdfcategory'),
    path('generate_pdfsubcategory', views.generate_pdfsubcategory, name='generate_pdfsubcategory'),
    path('generate_pdftutorial', views.generate_pdftutorial, name='generate_pdftutorial'),
    path('generate_pdfsales', views.generate_pdfsales, name='generate_pdfsales'),
    path('generate_pdfbilldiet/<int:id>/', views.generate_pdfbilldiet, name='generate_pdfbilldiet'),
    path('generate_pdfbilltrainer/<int:id>/', views.generate_pdfbilltrainer, name='generate_pdfbilltrainer'),
    path('feedbackview', views.feedbackview, name='feedbackview'),
]