# Generated by Django 5.0 on 2023-12-21 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_fname', models.CharField(max_length=10)),
                ('cust_lname', models.CharField(max_length=10)),
                ('cust_age', models.CharField(max_length=3)),
                ('cust_height', models.CharField(max_length=3)),
                ('cust_phno', models.CharField(max_length=10)),
                ('cust_prob', models.TextField(max_length=100)),
                ('cust_email', models.EmailField(max_length=254)),
                ('cust_pass', models.CharField(max_length=15)),
                ('cust_repass', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
