# Generated by Django 5.0 on 2023-12-22 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_customer',
            old_name='cust_pass',
            new_name='cust_password',
        ),
        migrations.RenameField(
            model_name='tbl_customer',
            old_name='cust_phno',
            new_name='cust_phone',
        ),
        migrations.RenameField(
            model_name='tbl_customer',
            old_name='cust_prob',
            new_name='cust_problem',
        ),
        migrations.RemoveField(
            model_name='tbl_customer',
            name='cust_repass',
        ),
    ]
