# Generated by Django 5.0 on 2023-12-22 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_rename_cust_pass_tbl_customer_cust_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_customer',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='', max_length=10),
        ),
        migrations.CreateModel(
            name='Tbl_Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(max_length=20)),
                ('trainer_age', models.PositiveIntegerField()),
                ('trainer_gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='', max_length=10)),
                ('trainer_email', models.EmailField(max_length=254)),
                ('trainer_phone', models.CharField(max_length=10)),
                ('trainer_certificate', models.FileField(upload_to='')),
                ('trainer_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
