# Generated by Django 5.0 on 2023-12-22 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_tbl_customer_gender_tbl_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_customer',
            name='cust_password',
        ),
    ]
