# Generated by Django 5.0 on 2023-12-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_remove_tbl_customer_cust_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_customer',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other'), ('', '')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='tbl_trainer',
            name='trainer_gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other'), ('', '')], default='', max_length=10),
        ),
    ]
