# Generated by Django 5.0 on 2023-12-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_tbl_trainer_trainer_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_customer',
            old_name='gender',
            new_name='cust_gender',
        ),
        migrations.AddField(
            model_name='tbl_trainer',
            name='trainer_level',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other'), ('', '')], default='', max_length=20),
        ),
    ]
