# Generated by Django 5.0 on 2024-01-03 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0007_rename_gender_tbl_customer_cust_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_desc', models.TextField()),
                ('category_image', models.ImageField(upload_to='category_image')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(choices=[('chest', 'chest'), ('shoulder', 'shoulder'), ('legs', 'legs'), ('back', 'back'), ('biceps', 'biceps'), ('triceps', 'triceps'), ('forearms', 'forearms'), ('abs', 'abs'), ('none', 'none')], default='none', max_length=50)),
                ('video', models.FileField(upload_to='videos')),
                ('reps', models.PositiveIntegerField(default=8)),
                ('sets', models.PositiveIntegerField(default=3)),
                ('rest_time', models.PositiveIntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.tbl_category')),
            ],
        ),
    ]
