# Generated by Django 5.0 on 2024-01-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0008_tbl_category_tbl_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_customer',
            name='cust_status',
            field=models.BooleanField(default=True),
        ),
    ]
