# Generated by Django 5.0 on 2024-01-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0009_tbl_customer_cust_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_trainer',
            name='trainer_approval',
            field=models.BooleanField(default=False),
        ),
    ]
