# Generated by Django 5.0 on 2024-01-18 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0010_tbl_trainer_trainer_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_subcategory',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='tbl_subcategory',
            name='rest_time',
        ),
        migrations.RemoveField(
            model_name='tbl_subcategory',
            name='sets',
        ),
        migrations.RemoveField(
            model_name='tbl_subcategory',
            name='video',
        ),
        migrations.CreateModel(
            name='Tbl_tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=50)),
                ('video', models.FileField(upload_to='videos')),
                ('reps', models.PositiveIntegerField(default=8)),
                ('sets', models.PositiveIntegerField(default=3)),
                ('rest_time', models.PositiveIntegerField(default=1)),
                ('sub_category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.tbl_subcategory')),
            ],
        ),
    ]
