# Generated by Django 5.0 on 2024-01-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0012_alter_tbl_trainer_trainer_level_tbl_card_tbl_diet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_payment',
            name='type',
            field=models.CharField(choices=[('D', 'Diet'), ('T', 'Trainer')], default='none', max_length=2),
        ),
    ]
