# Generated by Django 5.0 on 2024-01-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0014_alter_tbl_diet_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_payment',
            name='diet_or_trainer',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_card',
            name='cvv',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
