# Generated by Django 5.0 on 2024-01-31 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0015_tbl_payment_diet_or_trainer_alter_tbl_card_cvv'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_customer',
            name='cust_weight',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
