# Generated by Django 5.0 on 2024-02-12 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0016_tbl_customer_cust_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_payment',
            name='diet_or_trainer',
        ),
    ]
