# Generated by Django 5.0 on 2024-02-12 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0017_remove_tbl_payment_diet_or_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_trainer_assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.tbl_customer')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.tbl_payment')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.tbl_trainer')),
            ],
        ),
    ]
