# Generated by Django 5.0 on 2024-03-13 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0021_tbl_leaderboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('msg', models.TextField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.tbl_customer')),
            ],
        ),
    ]
